productを追加
impv/yamada-pricetouch pull request #3
Opened 2020-12-10 02:57 UTC by yukisagara

2020-12-10 08:20 UTC, oathkite requested changes

2020-12-10 08:20 UTC, oathkite commented on src/html/page/_product.html
> +        <a href="#" class="btn btn-menu btn-menu--b"><i class="icon"><img src="../img/icon-cart.svg"></i><span class="text">WEBCOM<br>で探す</span></a>
ボタンのデザインが変更になりました。状態が二つあって、
```
1. 通常状態
その他のボタンと同じ白地に青もじ・青アイコン

2. 在庫なし状態
赤地に白文字・白アイコン
```
2の状態はクラスを作っておいてもらえればと思います。

でお願いします。

2020-12-10 08:20 UTC, oathkite commented on src/scss/component/_list.scss
> +    justify-content: space-between;
ボタンの数が3つの場合があるらしく、その場合中央揃えにしたいとのことなので、 `center` に変更お願いします。

2020-12-10 08:20 UTC, oathkite commented on src/scss/component/_list.scss
> +    justify-content: space-between;
上記の設定するとマージンがなくなっちゃうので、ボタンにマージン設定をお願いします。

2020-12-10 08:20 UTC, oathkite commented on src/html/page/_product.html
> +    </dl>
このコンテンツはいくつか状態があるので、用意しておいてもらえるとありがたい。コメントアウトでOKです。

```
1. 在庫がある場合
現在の状態

2. 在庫がない場合
赤文字で在庫なし表示

3. 在庫を表示したくない場合
黒文字で係員にお問い合わせください表示
```

https://www.figma.com/file/if4IIDfDRauAZ0DIPV7El8/%E3%83%97%E3%83%A9%E3%82%A4%E3%82%B9%E3%82%BF%E3%83%83%E3%83%81UI?node-id=18%3A2439

2020-12-10 08:20 UTC, oathkite commented on src/html/page/_product.html
> +    </div>
レビューがない状態の表示も用意お願いします。コメントアウトでOKっす。

https://www.figma.com/file/if4IIDfDRauAZ0DIPV7El8/%E3%83%97%E3%83%A9%E3%82%A4%E3%82%B9%E3%82%BF%E3%83%83%E3%83%81UI?node-id=475%3A910

2020-12-11 01:59 UTC, yukisagara commented on src/html/page/_product.html
> +        <a href="#" class="btn btn-menu btn-menu--b"><i class="icon"><img src="../img/icon-cart.svg"></i><span class="text">WEBCOM<br>で探す</span></a>
こちら、修正いたしましたのでご確認をお願いします

2020-12-11 01:59 UTC, yukisagara commented on src/scss/component/_list.scss
> +    justify-content: space-between;
こちらボタンが3つの場合は中央揃えになるように対応しました。

2020-12-11 02:03 UTC, yukisagara commented on src/html/page/_product.html
> +    </dl>
「残りわずか」を削除し、「在庫がない場合」を追加しました。

2020-12-11 02:05 UTC, yukisagara commented on src/html/page/_product.html
> +    </div>
レビュー0件の状態のスタイルを追加しました。
星アイコン部分については、ひとまず`inactive`classでグレーアウトするようにしています。

2020-12-11 07:42 UTC, oathkite approved these changes

2020-12-11 09:22 UTC, merged