総合評価のスターのclassをフロント側でする
impv/yamada-pricetouch pull request #4
Opened 2020-12-22 07:31 UTC by yukisagara

## 変更内容
`data-score`の数値を元に`<li class="star"></li>`にclassを付与するようにしました。

## 確認用URL

2020-12-23 02:16 UTC, oathkite requested changes

2020-12-23 02:16 UTC, oathkite commented on src/html/product/review.html
> +    getStarScore(reviewTotal);
まるっとこんな感じでシンプルに置き換えられるので、一度みてみてください。
ES6の記述は古いAndroidとかで動かない恐れがあるので、今回は避けた方が良いと思う。

```suggestion
    var stars = document.querySelectorAll(".review-stars--total .star");
    var score = document.querySelector("#reviewTotal").dataset.score

    for(var i = 0; i < stars.length; i++) {   
        if (score / 100 * 5 < i + 1) {
            stars[i].classList.add("inactive")
        } else {
            stars[i].classList.add("fill")
        }
    }
```

2020-12-24 02:38 UTC, oathkite requested changes

2020-12-24 02:38 UTC, oathkite commented on src/html/page/_product.html
> +    console.log(score);
デバッグコード削除お願いします！

2020-12-24 02:38 UTC, oathkite commented on src/html/product/review.html
> +    console.log(score);
デバッグコード削除お願いします！

2020-12-24 02:41 UTC, yukisagara commented
ありがとうございます。
いただいたコメントを元に、修正しましたのでご確認をお願いいたします。

`<li class="star"></li>`の状態は下記の3つになっています。
 - `class="star"` → 黄色の枠線のみの状態
 - `class="star fill"` → 黄色に塗りつぶした状態
 - `class="star inactive"`  → グレーアウトの状態

2020-12-24 02:47 UTC, oathkite commented
状態がその三つなら実装少し調整したほうがいいかも。defaultがinactiveで、data-scoreがあった場合にfillかlineになるようにしたほうがいいかなと思った。

2020-12-24 03:02 UTC, yukisagara commented
`<li class="star"></li>`の状態を下記のように変更しましたのでご確認をお願いいたします

 - `class="star"` → グレーアウトの状態
 - `class="star line"` → 黄色の枠線のみの状態
 - `class="star fill"` → 黄色に塗りつぶした状態

2020-12-24 03:03 UTC, oathkite approved these changes

2020-12-24 03:04 UTC, oathkite commented
@yukisagara 🍎

2020-12-24 03:04 UTC, merged